server:
  port: 8081
spring:
  application:
    name: neo-presentation
  account-service.url : http://localhost:8080
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=book_service}
    username: ${USER_DB:postgres}
    password: ${PASSWORD_DB:123}
    driver-class-name: org.postgresql.Driver
  liquibase:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=book_service}
    user: ${USER_DB:postgres}
    password: ${PASSWORD_DB:123}
    change-log: classpath:db/changelog/db.changelog-master.yaml
    driver-class-name: org.postgresql.Driver
    liquibase-schema: book_service
    enabled: true